<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>c6adac2d-793e-4105-899e-18cf22180f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form[name=&quot;vmAdd.formAdd&quot;] > div.clearfix > div.pull-right > button.btn.button-secondary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>01af3f2b-b640-4fe6-97d3-3b64c9245f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-secondary</value>
      <webElementGuid>4f490def-b14e-48ce-8ce9-664d5ad14e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>aa07fb85-8c14-419c-ae3b-d1cb31dd9e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                 Save
            </value>
      <webElementGuid>6eed8e0a-db7d-432c-9bf8-5898a9277d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabsetTasksMain&quot;)/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;form-horizontal ng-valid-minlength ng-valid-maxlength ng-valid-min ng-valid-max ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;pull-right&quot;]/button[@class=&quot;btn button-secondary&quot;]</value>
      <webElementGuid>f7a2d803-7f19-4b8f-86c6-9ab55a187b65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[4]</value>
      <webElementGuid>1bdfd965-92bf-447a-a31a-489cc96ebc5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsetTasksMain']/div/div[3]/div/form/div/div/button</value>
      <webElementGuid>dfe08cab-f5bb-484b-ac4d-8fe92de9ea04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Task'])[2]/following::button[1]</value>
      <webElementGuid>d8371418-0805-4ea5-929e-1693929ec905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Wait...'])[8]/following::button[1]</value>
      <webElementGuid>985ad539-96f0-42cb-b775-688e2ef8a8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Task Name:'])[2]/preceding::button[2]</value>
      <webElementGuid>8a7ecbde-f404-40e4-a586-87a924fdb33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/form/div/div/button</value>
      <webElementGuid>f654864b-44a3-4bf8-aa24-a17740284896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                 Save
            ' or . = '
                 Save
            ')]</value>
      <webElementGuid>403c04ff-f686-4d4a-88a5-9c497dd7ac98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
