<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add or remove qualification methods, ad_941f7b</name>
   <tag></tag>
   <elementGuidId>aa6ee02d-232c-472d-804d-34e126f15f7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form[name=&quot;vmTasks.formEdit&quot;] > ewn-info-panel.ng-isolate-scope > div.panel.panel-body.has-error.alert-info > div.col-xs-11</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabsetTasksDetails']/div/div[2]/div/form/ewn-info-panel/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a00e17b-de95-4e20-96e5-366f62bcc8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-11</value>
      <webElementGuid>fa3e7685-a4a7-4310-a73f-53c6542ac7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add or remove qualification methods, add a new qualification option to a task, update a requalification interval, archive a qualification option or inactivate a qualification option.</value>
      <webElementGuid>eec49e0e-beb1-40ac-a0fc-c24a9e5b216b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabsetTasksDetails&quot;)/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;form-horizontal ng-valid ng-valid-required ng-dirty&quot;]/ewn-info-panel[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;panel panel-body has-error alert-info&quot;]/div[@class=&quot;col-xs-11&quot;]</value>
      <webElementGuid>7ff468b6-fa47-4833-8e09-c8e5e01c4cc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsetTasksDetails']/div/div[2]/div/form/ewn-info-panel/div/div[2]</value>
      <webElementGuid>b620479d-2d12-4d25-9245-6fa9c5918187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Wait...'])[2]/following::div[6]</value>
      <webElementGuid>c677c3f0-54c8-4d33-b25a-545d20d7ec63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Condition Status:'])[1]/preceding::div[1]</value>
      <webElementGuid>ed3d7a0b-9f3f-480f-b0d7-b60e107fe95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::div[1]</value>
      <webElementGuid>4aee69d6-89b7-418e-ac7e-f7166fd03480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/ewn-info-panel/div/div[2]</value>
      <webElementGuid>7ca36d64-52d6-484f-9a7c-67812764aae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add or remove qualification methods, add a new qualification option to a task, update a requalification interval, archive a qualification option or inactivate a qualification option.' or . = 'Add or remove qualification methods, add a new qualification option to a task, update a requalification interval, archive a qualification option or inactivate a qualification option.')]</value>
      <webElementGuid>4e2d3717-e2ff-45c5-8af8-2816f435692d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
