<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name  ID_uxTxtCompanyName</name>
   <tag></tag>
   <elementGuidId>99a0c314-1064-476c-b5fd-14bf284c444c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uxTxtCompanyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uxTxtCompanyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bded681a-41f2-47cd-9634-132f99e5c817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79b757f6-99e9-43e5-83fc-426f69ad874d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uxTxtCompanyName</value>
      <webElementGuid>1062c405-a638-4963-9ad8-b20145c9de1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uxTxtCompanyName</value>
      <webElementGuid>e1b52948-76f2-484b-853c-363406b7e49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>8c50c50c-bdc0-4258-b647-bef41850c3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmMain.criteria.companyName</value>
      <webElementGuid>106d2ae4-0661-4dfe-a1a5-1b6cc0adae53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uxTxtCompanyName&quot;)</value>
      <webElementGuid>0bbfc286-a0ca-4791-8a4c-bb29fb0dc901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uxTxtCompanyName']</value>
      <webElementGuid>3315d56d-9d3e-438e-805d-a1ffd7c821af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsetCompanyAccountMain']/div/div/div/form/div/div/div/input</value>
      <webElementGuid>42c7cb76-24d9-4b37-8a50-52fabab8f725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a1c540df-574e-47a9-aca8-b5f0702e0b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'uxTxtCompanyName' and @name = 'uxTxtCompanyName']</value>
      <webElementGuid>c167bfdf-5e20-46e8-9ea3-1815fe50320a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
