<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CRICKET_1_ng-pristine ng-untouched ng_7794ad</name>
   <tag></tag>
   <elementGuidId>123dece7-e07a-47c3-a13b-00608474b501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.col-sm-1.text-center > input.ng-pristine.ng-untouched.ng-valid.ng-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71401b5a-35b2-48f5-8a8d-3437ee55862b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1c4f0f9b-bfcb-4458-b981-cc46d80d5537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>t.isSelected</value>
      <webElementGuid>79ce86d1-5356-4070-a9f6-63e7cfd7f3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>vmTasks.updateItemSelected(t, condition.selectedItems, 'isSelected')</value>
      <webElementGuid>bec0f1c0-2bc9-4212-9c81-c63a8712040d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>113119d2-b4a5-42e4-b0a1-c9950723393e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabsetTasksDetails&quot;)/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/div[@class=&quot;ng-scope&quot;]/form[@class=&quot;form-horizontal ng-valid ng-valid-required ng-dirty&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/table[@class=&quot;table table-condensed table-striped ng-scope ng-table&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;col-sm-1 text-center&quot;]/input[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>46495377-bff8-4c8c-86df-7203a9ea2053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[2]</value>
      <webElementGuid>07789a02-f76e-4252-9eb1-fc1268071fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsetTasksDetails']/div/div[2]/div/form/div[3]/div[2]/table/tbody/tr/td[12]/input</value>
      <webElementGuid>bdc6ee1e-1e84-4517-be16-d1cab756a7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/input</value>
      <webElementGuid>d3481c95-8631-47da-9cb5-2f2b7eedf572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>7c0b6c78-b3a3-4fb9-837b-f876ef939bea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
