<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Task Name_txtTasksPropertiesTaskName</name>
   <tag></tag>
   <elementGuidId>a408e429-8da1-4858-a052-d26b4f3a3c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtTasksPropertiesTaskName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtTasksPropertiesTaskName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>505d3b31-449a-4584-af9e-9598791e97c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtTasksPropertiesTaskName</value>
      <webElementGuid>da19deed-96a1-488b-a80f-29e297f8888a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtTasksPropertiesTaskName</value>
      <webElementGuid>a58327ce-c040-4274-b1d1-908eb484efe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f60897df-e109-4bbd-8074-13cd9dfd75b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength</value>
      <webElementGuid>0dec6434-23c0-4bb1-858a-333c30d38140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>vmAdd.task.name</value>
      <webElementGuid>600dda1e-8c5f-4448-90b6-08d84642da82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>vmAdd.isCopyMode &amp;&amp; !vmAdd.task.copyFromTaskId</value>
      <webElementGuid>3a7ba140-170f-45d5-9586-4f4358148044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9ffbe671-a3ad-46ea-8fc2-8e6877c3e449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>350</value>
      <webElementGuid>7ab64d46-e7ff-4948-b9b4-74937897decc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtTasksPropertiesTaskName&quot;)</value>
      <webElementGuid>3b1df2e8-517b-43b4-8722-53443ca17335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtTasksPropertiesTaskName']</value>
      <webElementGuid>04e2ee03-b377-4300-bc74-69292ce1102a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsetTasksMain']/div/div[3]/div/form/div[2]/div/div/input</value>
      <webElementGuid>617ce090-53fd-4943-8cbc-ec0181aa41d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/input</value>
      <webElementGuid>0e0349e7-fe3f-4467-90a2-1bb7c19fdd1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtTasksPropertiesTaskName' and @name = 'txtTasksPropertiesTaskName' and @type = 'text']</value>
      <webElementGuid>f143e18d-de2a-4f60-b7b7-788cb1b74f0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
