<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Active_btn ri-user-search-line</name>
   <tag></tag>
   <elementGuidId>d836989a-7458-48c3-8c34-c3cb77bd240f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabsetCompanyAccountMain']/div/div/div/div/table/tbody/tr[2]/td[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dca4c66c-59d3-46e4-b688-bcb3e125ae56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn ri-user-search-line</value>
      <webElementGuid>454c058d-3a44-40b3-9389-a02b80cf49db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>vmMain.viewCompanyUsers(t)</value>
      <webElementGuid>ab509115-4ccb-4c15-9b38-f8bffc299850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabsetCompanyAccountMain&quot;)/div[@class=&quot;tab-content&quot;]/div[@class=&quot;tab-pane ng-scope active&quot;]/div[@class=&quot;ng-scope&quot;]/div[1]/table[@class=&quot;table table-striped ng-scope ng-table&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;text-center button-cell&quot;]/span[@class=&quot;btn ri-user-search-line&quot;]</value>
      <webElementGuid>84019a2e-9cfd-4804-abff-390d0c30f418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsetCompanyAccountMain']/div/div/div/div/table/tbody/tr[2]/td[3]/span</value>
      <webElementGuid>fc2287d3-f97b-4bc8-ae43-b02c4516e0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/span</value>
      <webElementGuid>948f29ea-6897-47c2-a6a9-4faf887fd242</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
