<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_My Requirements</name>
   <tag></tag>
   <elementGuidId>3caba528-ba45-4a43-87c8-721d7dbd8020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.panel-title.side-menu-panel-header > a > span.ng-binding</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-menu']/div/uib-accordion/div/div/div/div/div/div/div/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6743fa35-cc3a-4bc3-bdbe-9dc02b88407d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>com.title</value>
      <webElementGuid>cdab444b-da3c-4eab-8cd4-40b7351fd3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>1a015e56-088c-4e54-9016-4abe808203a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Requirements</value>
      <webElementGuid>44d552b7-4163-4b8b-b3f8-0dde20a1e4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-menu&quot;)/div[@class=&quot;ng-scope&quot;]/uib-accordion[@class=&quot;accordion accordion-menu&quot;]/div[@class=&quot;panel-group&quot;]/div[@class=&quot;side-menu-container ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;panel panel-primary&quot;]/div[@class=&quot;panel-heading accordion-menu-panel-header&quot;]/div[@class=&quot;panel-title side-menu-panel-header&quot;]/a[1]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>d2c5b1f1-69a7-405c-8f48-b7864f42b843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-menu']/div/uib-accordion/div/div/div/div/div/div/div/a/span[2]</value>
      <webElementGuid>9f9d403c-4281-490e-b21f-f3003fd0c25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Toolbox'])[1]/following::span[2]</value>
      <webElementGuid>8584a5a7-7abc-4bb6-aeef-ccb5bab48de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live Chat with an Expert'])[1]/following::span[4]</value>
      <webElementGuid>bd0ca909-944f-4a1e-8b86-9f9fe8bce951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/preceding::span[2]</value>
      <webElementGuid>1fa7ec86-4fc4-4962-b628-d0d53f912294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification Center'])[1]/preceding::span[4]</value>
      <webElementGuid>9e8fdde7-a918-4969-8c4d-0b4b94a48380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Requirements']/parent::*</value>
      <webElementGuid>4c28012b-9635-4068-a69b-2acc86ffb90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span[2]</value>
      <webElementGuid>35be2a69-cbd7-4286-bff0-550e81f95f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'My Requirements' or . = 'My Requirements')]</value>
      <webElementGuid>3b36665a-e277-41c2-8a1b-b1d0840791cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
