<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add_ri-arrow-down-s-line</name>
   <tag></tag>
   <elementGuidId>bd23e7db-3c91-4ee8-beec-5235c9693368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ri-arrow-down-s-line</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-content']/div/div[2]/button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fdc742cd-0b65-41a5-b8d4-8ffdea3c8812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ri-arrow-down-s-line</value>
      <webElementGuid>50b73547-84a5-4274-9735-68f3a42c53cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-content&quot;)/div[@class=&quot;product-section ng-scope&quot;]/div[@class=&quot;btn-group pull-right ng-scope dropdown&quot;]/button[@class=&quot;btn button-primary dropdown-toggle&quot;]/span[@class=&quot;ri-arrow-down-s-line&quot;]</value>
      <webElementGuid>26e325d1-407f-4847-b93c-1e1d1540ba04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-content']/div/div[2]/button/span[2]</value>
      <webElementGuid>dfbd4ab4-ad93-425e-b9a0-6a010236df05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>7ca67033-444a-4695-a286-b2ec2ab806b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
