<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uib-tab-heading_Conditions</name>
   <tag></tag>
   <elementGuidId>b84bb283-57a6-4865-bff1-8d5250c9de24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabTasksDetailsEdit > a.ng-binding > uib-tab-heading.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tabTasksDetailsEdit']/a/uib-tab-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>uib-tab-heading</value>
      <webElementGuid>34b5d6f7-726a-4282-bee4-54f4c78ec061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>8fba7c48-6b24-4cdf-b03b-afc5040669f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Conditions</value>
      <webElementGuid>8e6150ad-2fca-4b6b-a1d3-ecbfc3442603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabTasksDetailsEdit&quot;)/a[@class=&quot;ng-binding&quot;]/uib-tab-heading[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>30d4cc10-651b-4862-a8f1-691e9950dce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tabTasksDetailsEdit']/a/uib-tab-heading</value>
      <webElementGuid>83607085-3af7-4a76-9499-9bcb8e9450e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Properties'])[1]/following::uib-tab-heading[1]</value>
      <webElementGuid>93164b5c-11cf-45bb-b128-5e339197a9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[1]/following::uib-tab-heading[2]</value>
      <webElementGuid>64808e82-f6f4-467f-b073-a2b25d2a82cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conditions'])[2]/preceding::uib-tab-heading[1]</value>
      <webElementGuid>bb1d73b2-a945-4991-8c4d-14e6c99c680f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='References'])[1]/preceding::uib-tab-heading[2]</value>
      <webElementGuid>2a87f6f4-fa3b-41d5-9b65-c655ebc98ce1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Conditions']/parent::*</value>
      <webElementGuid>daab9b58-96a5-4b2e-ba88-ce5f8bfd8ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/ul/li[2]/a/uib-tab-heading</value>
      <webElementGuid>29054e44-a0ac-408f-9ed2-b6724b6e510f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//uib-tab-heading[(text() = ' Conditions' or . = ' Conditions')]</value>
      <webElementGuid>9107f45c-b1a5-4164-976c-1c72490fffbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
