<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uib-tab-heading_Search</name>
   <tag></tag>
   <elementGuidId>9b6ed548-32a4-4178-8e56-6d9e8ae72745</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>uib-tab-heading.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tabCompanySearch']/a/uib-tab-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>uib-tab-heading</value>
      <webElementGuid>83827720-61f7-4c05-ab7e-61f46246dcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>uib-tooltip</name>
      <type>Main</type>
      <value>Search and view companies</value>
      <webElementGuid>91f2f61c-a535-4244-86fa-adb35fd6e258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltip-placement</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>fef8862f-1d83-417d-ab39-20a1ee81acf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>3f61e23b-689c-4a4a-853b-26b5875f2a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Search</value>
      <webElementGuid>c614a47e-d6f5-4710-ba5f-ffa8e3821830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabCompanySearch&quot;)/a[@class=&quot;ng-binding&quot;]/uib-tab-heading[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>61a2c37e-13a6-4b6f-9758-645dbe9116b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='tabCompanySearch']/a/uib-tab-heading</value>
      <webElementGuid>263e4839-a33a-403a-a8fb-253c1f5d4a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Third-Party Evaluator'])[1]/following::uib-tab-heading[1]</value>
      <webElementGuid>0430e7f5-ea2a-4bc7-87af-49c3ffe61d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Applicant'])[1]/following::uib-tab-heading[1]</value>
      <webElementGuid>7ba32c5a-db7b-4d43-a408-9c974affa242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search and view companies'])[1]/preceding::uib-tab-heading[1]</value>
      <webElementGuid>127d47e8-3359-4743-8d82-25d8ec16c20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/preceding::uib-tab-heading[1]</value>
      <webElementGuid>a9d3c407-b54f-4dc2-a039-59d28db32361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//uib-tab-heading</value>
      <webElementGuid>aa25f0bc-f345-40c4-9025-36b7e5296d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//uib-tab-heading[(text() = ' Search' or . = ' Search')]</value>
      <webElementGuid>f26d5e98-d606-4ae4-aa14-17ba86b9b6c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
